/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateC4bhFormDataInput = {
  id?: string | null,
  Participant: boolean,
  ParticipantID?: string | null,
  EhrIntersystems?: boolean | null,
  EhrSmile?: boolean | null,
  EhrSalesforce?: boolean | null,
  EhrOther?: string | null,
  SendOutboundDirect?: boolean | null,
  SendOutboundSFTP?: boolean | null,
  SendOutboundMLLP?: boolean | null,
  SendOutboundHTTPS?: boolean | null,
  SendOutboundFHIR?: boolean | null,
  SendOutboundNone?: boolean | null,
  SendInformationDirect?: boolean | null,
  SendInformationSFTP?: boolean | null,
  SendInformationMLLP?: boolean | null,
  SendInformationHTTPS?: boolean | null,
  SendInformationFHIR?: boolean | null,
  SendInformationIHE?: boolean | null,
  SendInformationNone?: boolean | null,
  SendRequestDirect?: boolean | null,
  SendRequestSFTP?: boolean | null,
  SendRequestFHIR?: boolean | null,
  SendRequestIHE?: boolean | null,
  SendRequestNone?: boolean | null,
  ReceiveInboundDirect?: boolean | null,
  ReceiveInboundSFTP?: boolean | null,
  ReceiveInboundMLLP?: boolean | null,
  ReceiveInboundHTTPS?: boolean | null,
  ReceiveInboundFHIR?: boolean | null,
  ReceiveInboundNone?: boolean | null,
  ReceiveInformationDirect?: boolean | null,
  ReceiveInformationSFTP?: boolean | null,
  ReceiveInformationMLLP?: boolean | null,
  ReceiveInformationHTTPS?: boolean | null,
  ReceiveInformationFHIR?: boolean | null,
  ReceiveInformationIHE?: boolean | null,
  ReceiveInformationNone?: boolean | null,
  ReceiveRequestDirect?: boolean | null,
  ReceiveRequestSFTP?: boolean | null,
  ReceiveRequestFHIR?: boolean | null,
  ReceiveRequestIHE?: boolean | null,
  ReceiveRequestNone?: boolean | null,
  HIPPA?: boolean | null,
};

export type ModelC4bhFormDataConditionInput = {
  Participant?: ModelBooleanInput | null,
  ParticipantID?: ModelStringInput | null,
  EhrIntersystems?: ModelBooleanInput | null,
  EhrSmile?: ModelBooleanInput | null,
  EhrSalesforce?: ModelBooleanInput | null,
  EhrOther?: ModelStringInput | null,
  SendOutboundDirect?: ModelBooleanInput | null,
  SendOutboundSFTP?: ModelBooleanInput | null,
  SendOutboundMLLP?: ModelBooleanInput | null,
  SendOutboundHTTPS?: ModelBooleanInput | null,
  SendOutboundFHIR?: ModelBooleanInput | null,
  SendOutboundNone?: ModelBooleanInput | null,
  SendInformationDirect?: ModelBooleanInput | null,
  SendInformationSFTP?: ModelBooleanInput | null,
  SendInformationMLLP?: ModelBooleanInput | null,
  SendInformationHTTPS?: ModelBooleanInput | null,
  SendInformationFHIR?: ModelBooleanInput | null,
  SendInformationIHE?: ModelBooleanInput | null,
  SendInformationNone?: ModelBooleanInput | null,
  SendRequestDirect?: ModelBooleanInput | null,
  SendRequestSFTP?: ModelBooleanInput | null,
  SendRequestFHIR?: ModelBooleanInput | null,
  SendRequestIHE?: ModelBooleanInput | null,
  SendRequestNone?: ModelBooleanInput | null,
  ReceiveInboundDirect?: ModelBooleanInput | null,
  ReceiveInboundSFTP?: ModelBooleanInput | null,
  ReceiveInboundMLLP?: ModelBooleanInput | null,
  ReceiveInboundHTTPS?: ModelBooleanInput | null,
  ReceiveInboundFHIR?: ModelBooleanInput | null,
  ReceiveInboundNone?: ModelBooleanInput | null,
  ReceiveInformationDirect?: ModelBooleanInput | null,
  ReceiveInformationSFTP?: ModelBooleanInput | null,
  ReceiveInformationMLLP?: ModelBooleanInput | null,
  ReceiveInformationHTTPS?: ModelBooleanInput | null,
  ReceiveInformationFHIR?: ModelBooleanInput | null,
  ReceiveInformationIHE?: ModelBooleanInput | null,
  ReceiveInformationNone?: ModelBooleanInput | null,
  ReceiveRequestDirect?: ModelBooleanInput | null,
  ReceiveRequestSFTP?: ModelBooleanInput | null,
  ReceiveRequestFHIR?: ModelBooleanInput | null,
  ReceiveRequestIHE?: ModelBooleanInput | null,
  ReceiveRequestNone?: ModelBooleanInput | null,
  HIPPA?: ModelBooleanInput | null,
  and?: Array< ModelC4bhFormDataConditionInput | null > | null,
  or?: Array< ModelC4bhFormDataConditionInput | null > | null,
  not?: ModelC4bhFormDataConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type C4bhFormData = {
  __typename: "C4bhFormData",
  id: string,
  Participant: boolean,
  ParticipantID?: string | null,
  EhrIntersystems?: boolean | null,
  EhrSmile?: boolean | null,
  EhrSalesforce?: boolean | null,
  EhrOther?: string | null,
  SendOutboundDirect?: boolean | null,
  SendOutboundSFTP?: boolean | null,
  SendOutboundMLLP?: boolean | null,
  SendOutboundHTTPS?: boolean | null,
  SendOutboundFHIR?: boolean | null,
  SendOutboundNone?: boolean | null,
  SendInformationDirect?: boolean | null,
  SendInformationSFTP?: boolean | null,
  SendInformationMLLP?: boolean | null,
  SendInformationHTTPS?: boolean | null,
  SendInformationFHIR?: boolean | null,
  SendInformationIHE?: boolean | null,
  SendInformationNone?: boolean | null,
  SendRequestDirect?: boolean | null,
  SendRequestSFTP?: boolean | null,
  SendRequestFHIR?: boolean | null,
  SendRequestIHE?: boolean | null,
  SendRequestNone?: boolean | null,
  ReceiveInboundDirect?: boolean | null,
  ReceiveInboundSFTP?: boolean | null,
  ReceiveInboundMLLP?: boolean | null,
  ReceiveInboundHTTPS?: boolean | null,
  ReceiveInboundFHIR?: boolean | null,
  ReceiveInboundNone?: boolean | null,
  ReceiveInformationDirect?: boolean | null,
  ReceiveInformationSFTP?: boolean | null,
  ReceiveInformationMLLP?: boolean | null,
  ReceiveInformationHTTPS?: boolean | null,
  ReceiveInformationFHIR?: boolean | null,
  ReceiveInformationIHE?: boolean | null,
  ReceiveInformationNone?: boolean | null,
  ReceiveRequestDirect?: boolean | null,
  ReceiveRequestSFTP?: boolean | null,
  ReceiveRequestFHIR?: boolean | null,
  ReceiveRequestIHE?: boolean | null,
  ReceiveRequestNone?: boolean | null,
  HIPPA?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateC4bhFormDataInput = {
  id: string,
  Participant?: boolean | null,
  ParticipantID?: string | null,
  EhrIntersystems?: boolean | null,
  EhrSmile?: boolean | null,
  EhrSalesforce?: boolean | null,
  EhrOther?: string | null,
  SendOutboundDirect?: boolean | null,
  SendOutboundSFTP?: boolean | null,
  SendOutboundMLLP?: boolean | null,
  SendOutboundHTTPS?: boolean | null,
  SendOutboundFHIR?: boolean | null,
  SendOutboundNone?: boolean | null,
  SendInformationDirect?: boolean | null,
  SendInformationSFTP?: boolean | null,
  SendInformationMLLP?: boolean | null,
  SendInformationHTTPS?: boolean | null,
  SendInformationFHIR?: boolean | null,
  SendInformationIHE?: boolean | null,
  SendInformationNone?: boolean | null,
  SendRequestDirect?: boolean | null,
  SendRequestSFTP?: boolean | null,
  SendRequestFHIR?: boolean | null,
  SendRequestIHE?: boolean | null,
  SendRequestNone?: boolean | null,
  ReceiveInboundDirect?: boolean | null,
  ReceiveInboundSFTP?: boolean | null,
  ReceiveInboundMLLP?: boolean | null,
  ReceiveInboundHTTPS?: boolean | null,
  ReceiveInboundFHIR?: boolean | null,
  ReceiveInboundNone?: boolean | null,
  ReceiveInformationDirect?: boolean | null,
  ReceiveInformationSFTP?: boolean | null,
  ReceiveInformationMLLP?: boolean | null,
  ReceiveInformationHTTPS?: boolean | null,
  ReceiveInformationFHIR?: boolean | null,
  ReceiveInformationIHE?: boolean | null,
  ReceiveInformationNone?: boolean | null,
  ReceiveRequestDirect?: boolean | null,
  ReceiveRequestSFTP?: boolean | null,
  ReceiveRequestFHIR?: boolean | null,
  ReceiveRequestIHE?: boolean | null,
  ReceiveRequestNone?: boolean | null,
  HIPPA?: boolean | null,
};

export type DeleteC4bhFormDataInput = {
  id: string,
};

export type ModelC4bhFormDataFilterInput = {
  id?: ModelIDInput | null,
  Participant?: ModelBooleanInput | null,
  ParticipantID?: ModelStringInput | null,
  EhrIntersystems?: ModelBooleanInput | null,
  EhrSmile?: ModelBooleanInput | null,
  EhrSalesforce?: ModelBooleanInput | null,
  EhrOther?: ModelStringInput | null,
  SendOutboundDirect?: ModelBooleanInput | null,
  SendOutboundSFTP?: ModelBooleanInput | null,
  SendOutboundMLLP?: ModelBooleanInput | null,
  SendOutboundHTTPS?: ModelBooleanInput | null,
  SendOutboundFHIR?: ModelBooleanInput | null,
  SendOutboundNone?: ModelBooleanInput | null,
  SendInformationDirect?: ModelBooleanInput | null,
  SendInformationSFTP?: ModelBooleanInput | null,
  SendInformationMLLP?: ModelBooleanInput | null,
  SendInformationHTTPS?: ModelBooleanInput | null,
  SendInformationFHIR?: ModelBooleanInput | null,
  SendInformationIHE?: ModelBooleanInput | null,
  SendInformationNone?: ModelBooleanInput | null,
  SendRequestDirect?: ModelBooleanInput | null,
  SendRequestSFTP?: ModelBooleanInput | null,
  SendRequestFHIR?: ModelBooleanInput | null,
  SendRequestIHE?: ModelBooleanInput | null,
  SendRequestNone?: ModelBooleanInput | null,
  ReceiveInboundDirect?: ModelBooleanInput | null,
  ReceiveInboundSFTP?: ModelBooleanInput | null,
  ReceiveInboundMLLP?: ModelBooleanInput | null,
  ReceiveInboundHTTPS?: ModelBooleanInput | null,
  ReceiveInboundFHIR?: ModelBooleanInput | null,
  ReceiveInboundNone?: ModelBooleanInput | null,
  ReceiveInformationDirect?: ModelBooleanInput | null,
  ReceiveInformationSFTP?: ModelBooleanInput | null,
  ReceiveInformationMLLP?: ModelBooleanInput | null,
  ReceiveInformationHTTPS?: ModelBooleanInput | null,
  ReceiveInformationFHIR?: ModelBooleanInput | null,
  ReceiveInformationIHE?: ModelBooleanInput | null,
  ReceiveInformationNone?: ModelBooleanInput | null,
  ReceiveRequestDirect?: ModelBooleanInput | null,
  ReceiveRequestSFTP?: ModelBooleanInput | null,
  ReceiveRequestFHIR?: ModelBooleanInput | null,
  ReceiveRequestIHE?: ModelBooleanInput | null,
  ReceiveRequestNone?: ModelBooleanInput | null,
  HIPPA?: ModelBooleanInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelC4bhFormDataFilterInput | null > | null,
  or?: Array< ModelC4bhFormDataFilterInput | null > | null,
  not?: ModelC4bhFormDataFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelC4bhFormDataConnection = {
  __typename: "ModelC4bhFormDataConnection",
  items:  Array<C4bhFormData | null >,
  nextToken?: string | null,
};

export type ModelSubscriptionC4bhFormDataFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  Participant?: ModelSubscriptionBooleanInput | null,
  ParticipantID?: ModelSubscriptionStringInput | null,
  EhrIntersystems?: ModelSubscriptionBooleanInput | null,
  EhrSmile?: ModelSubscriptionBooleanInput | null,
  EhrSalesforce?: ModelSubscriptionBooleanInput | null,
  EhrOther?: ModelSubscriptionStringInput | null,
  SendOutboundDirect?: ModelSubscriptionBooleanInput | null,
  SendOutboundSFTP?: ModelSubscriptionBooleanInput | null,
  SendOutboundMLLP?: ModelSubscriptionBooleanInput | null,
  SendOutboundHTTPS?: ModelSubscriptionBooleanInput | null,
  SendOutboundFHIR?: ModelSubscriptionBooleanInput | null,
  SendOutboundNone?: ModelSubscriptionBooleanInput | null,
  SendInformationDirect?: ModelSubscriptionBooleanInput | null,
  SendInformationSFTP?: ModelSubscriptionBooleanInput | null,
  SendInformationMLLP?: ModelSubscriptionBooleanInput | null,
  SendInformationHTTPS?: ModelSubscriptionBooleanInput | null,
  SendInformationFHIR?: ModelSubscriptionBooleanInput | null,
  SendInformationIHE?: ModelSubscriptionBooleanInput | null,
  SendInformationNone?: ModelSubscriptionBooleanInput | null,
  SendRequestDirect?: ModelSubscriptionBooleanInput | null,
  SendRequestSFTP?: ModelSubscriptionBooleanInput | null,
  SendRequestFHIR?: ModelSubscriptionBooleanInput | null,
  SendRequestIHE?: ModelSubscriptionBooleanInput | null,
  SendRequestNone?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundDirect?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundSFTP?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundMLLP?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundHTTPS?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundFHIR?: ModelSubscriptionBooleanInput | null,
  ReceiveInboundNone?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationDirect?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationSFTP?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationMLLP?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationHTTPS?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationFHIR?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationIHE?: ModelSubscriptionBooleanInput | null,
  ReceiveInformationNone?: ModelSubscriptionBooleanInput | null,
  ReceiveRequestDirect?: ModelSubscriptionBooleanInput | null,
  ReceiveRequestSFTP?: ModelSubscriptionBooleanInput | null,
  ReceiveRequestFHIR?: ModelSubscriptionBooleanInput | null,
  ReceiveRequestIHE?: ModelSubscriptionBooleanInput | null,
  ReceiveRequestNone?: ModelSubscriptionBooleanInput | null,
  HIPPA?: ModelSubscriptionBooleanInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionC4bhFormDataFilterInput | null > | null,
  or?: Array< ModelSubscriptionC4bhFormDataFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type CreateC4bhFormDataMutationVariables = {
  input: CreateC4bhFormDataInput,
  condition?: ModelC4bhFormDataConditionInput | null,
};

export type CreateC4bhFormDataMutation = {
  createC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateC4bhFormDataMutationVariables = {
  input: UpdateC4bhFormDataInput,
  condition?: ModelC4bhFormDataConditionInput | null,
};

export type UpdateC4bhFormDataMutation = {
  updateC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteC4bhFormDataMutationVariables = {
  input: DeleteC4bhFormDataInput,
  condition?: ModelC4bhFormDataConditionInput | null,
};

export type DeleteC4bhFormDataMutation = {
  deleteC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetC4bhFormDataQueryVariables = {
  id: string,
};

export type GetC4bhFormDataQuery = {
  getC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListC4bhFormDataQueryVariables = {
  filter?: ModelC4bhFormDataFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListC4bhFormDataQuery = {
  listC4bhFormData?:  {
    __typename: "ModelC4bhFormDataConnection",
    items:  Array< {
      __typename: "C4bhFormData",
      id: string,
      Participant: boolean,
      ParticipantID?: string | null,
      EhrIntersystems?: boolean | null,
      EhrSmile?: boolean | null,
      EhrSalesforce?: boolean | null,
      EhrOther?: string | null,
      SendOutboundDirect?: boolean | null,
      SendOutboundSFTP?: boolean | null,
      SendOutboundMLLP?: boolean | null,
      SendOutboundHTTPS?: boolean | null,
      SendOutboundFHIR?: boolean | null,
      SendOutboundNone?: boolean | null,
      SendInformationDirect?: boolean | null,
      SendInformationSFTP?: boolean | null,
      SendInformationMLLP?: boolean | null,
      SendInformationHTTPS?: boolean | null,
      SendInformationFHIR?: boolean | null,
      SendInformationIHE?: boolean | null,
      SendInformationNone?: boolean | null,
      SendRequestDirect?: boolean | null,
      SendRequestSFTP?: boolean | null,
      SendRequestFHIR?: boolean | null,
      SendRequestIHE?: boolean | null,
      SendRequestNone?: boolean | null,
      ReceiveInboundDirect?: boolean | null,
      ReceiveInboundSFTP?: boolean | null,
      ReceiveInboundMLLP?: boolean | null,
      ReceiveInboundHTTPS?: boolean | null,
      ReceiveInboundFHIR?: boolean | null,
      ReceiveInboundNone?: boolean | null,
      ReceiveInformationDirect?: boolean | null,
      ReceiveInformationSFTP?: boolean | null,
      ReceiveInformationMLLP?: boolean | null,
      ReceiveInformationHTTPS?: boolean | null,
      ReceiveInformationFHIR?: boolean | null,
      ReceiveInformationIHE?: boolean | null,
      ReceiveInformationNone?: boolean | null,
      ReceiveRequestDirect?: boolean | null,
      ReceiveRequestSFTP?: boolean | null,
      ReceiveRequestFHIR?: boolean | null,
      ReceiveRequestIHE?: boolean | null,
      ReceiveRequestNone?: boolean | null,
      HIPPA?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateC4bhFormDataSubscriptionVariables = {
  filter?: ModelSubscriptionC4bhFormDataFilterInput | null,
};

export type OnCreateC4bhFormDataSubscription = {
  onCreateC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateC4bhFormDataSubscriptionVariables = {
  filter?: ModelSubscriptionC4bhFormDataFilterInput | null,
};

export type OnUpdateC4bhFormDataSubscription = {
  onUpdateC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteC4bhFormDataSubscriptionVariables = {
  filter?: ModelSubscriptionC4bhFormDataFilterInput | null,
};

export type OnDeleteC4bhFormDataSubscription = {
  onDeleteC4bhFormData?:  {
    __typename: "C4bhFormData",
    id: string,
    Participant: boolean,
    ParticipantID?: string | null,
    EhrIntersystems?: boolean | null,
    EhrSmile?: boolean | null,
    EhrSalesforce?: boolean | null,
    EhrOther?: string | null,
    SendOutboundDirect?: boolean | null,
    SendOutboundSFTP?: boolean | null,
    SendOutboundMLLP?: boolean | null,
    SendOutboundHTTPS?: boolean | null,
    SendOutboundFHIR?: boolean | null,
    SendOutboundNone?: boolean | null,
    SendInformationDirect?: boolean | null,
    SendInformationSFTP?: boolean | null,
    SendInformationMLLP?: boolean | null,
    SendInformationHTTPS?: boolean | null,
    SendInformationFHIR?: boolean | null,
    SendInformationIHE?: boolean | null,
    SendInformationNone?: boolean | null,
    SendRequestDirect?: boolean | null,
    SendRequestSFTP?: boolean | null,
    SendRequestFHIR?: boolean | null,
    SendRequestIHE?: boolean | null,
    SendRequestNone?: boolean | null,
    ReceiveInboundDirect?: boolean | null,
    ReceiveInboundSFTP?: boolean | null,
    ReceiveInboundMLLP?: boolean | null,
    ReceiveInboundHTTPS?: boolean | null,
    ReceiveInboundFHIR?: boolean | null,
    ReceiveInboundNone?: boolean | null,
    ReceiveInformationDirect?: boolean | null,
    ReceiveInformationSFTP?: boolean | null,
    ReceiveInformationMLLP?: boolean | null,
    ReceiveInformationHTTPS?: boolean | null,
    ReceiveInformationFHIR?: boolean | null,
    ReceiveInformationIHE?: boolean | null,
    ReceiveInformationNone?: boolean | null,
    ReceiveRequestDirect?: boolean | null,
    ReceiveRequestSFTP?: boolean | null,
    ReceiveRequestFHIR?: boolean | null,
    ReceiveRequestIHE?: boolean | null,
    ReceiveRequestNone?: boolean | null,
    HIPPA?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
