/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
import { C4bhFormData } from "../models";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type C4bhFormDataUpdateFormInputValues = {
    Participant?: boolean;
    ParticipantID?: string;
    EhrIntersystems?: boolean;
    EhrSmile?: boolean;
    EhrSalesforce?: boolean;
    EhrOther?: string;
    SendOutboundDirect?: boolean;
    SendOutboundSFTP?: boolean;
    SendOutboundMLLP?: boolean;
    SendOutboundHTTPS?: boolean;
    SendOutboundFHIR?: boolean;
    SendOutboundNone?: boolean;
    SendInformationDirect?: boolean;
    SendInformationSFTP?: boolean;
    SendInformationMLLP?: boolean;
    SendInformationHTTPS?: boolean;
    SendInformationFHIR?: boolean;
    SendInformationIHE?: boolean;
    SendInformationNone?: boolean;
    SendRequestDirect?: boolean;
    SendRequestSFTP?: boolean;
    SendRequestFHIR?: boolean;
    SendRequestIHE?: boolean;
    SendRequestNone?: boolean;
    ReceiveInboundDirect?: boolean;
    ReceiveInboundSFTP?: boolean;
    ReceiveInboundMLLP?: boolean;
    ReceiveInboundHTTPS?: boolean;
    ReceiveInboundFHIR?: boolean;
    ReceiveInboundNone?: boolean;
    ReceiveInformationDirect?: boolean;
    ReceiveInformationSFTP?: boolean;
    ReceiveInformationMLLP?: boolean;
    ReceiveInformationHTTPS?: boolean;
    ReceiveInformationFHIR?: boolean;
    ReceiveInformationIHE?: boolean;
    ReceiveInformationNone?: boolean;
    ReceiveRequestDirect?: boolean;
    ReceiveRequestSFTP?: boolean;
    ReceiveRequestFHIR?: boolean;
    ReceiveRequestIHE?: boolean;
    ReceiveRequestNone?: boolean;
    HIPPA?: boolean;
};
export declare type C4bhFormDataUpdateFormValidationValues = {
    Participant?: ValidationFunction<boolean>;
    ParticipantID?: ValidationFunction<string>;
    EhrIntersystems?: ValidationFunction<boolean>;
    EhrSmile?: ValidationFunction<boolean>;
    EhrSalesforce?: ValidationFunction<boolean>;
    EhrOther?: ValidationFunction<string>;
    SendOutboundDirect?: ValidationFunction<boolean>;
    SendOutboundSFTP?: ValidationFunction<boolean>;
    SendOutboundMLLP?: ValidationFunction<boolean>;
    SendOutboundHTTPS?: ValidationFunction<boolean>;
    SendOutboundFHIR?: ValidationFunction<boolean>;
    SendOutboundNone?: ValidationFunction<boolean>;
    SendInformationDirect?: ValidationFunction<boolean>;
    SendInformationSFTP?: ValidationFunction<boolean>;
    SendInformationMLLP?: ValidationFunction<boolean>;
    SendInformationHTTPS?: ValidationFunction<boolean>;
    SendInformationFHIR?: ValidationFunction<boolean>;
    SendInformationIHE?: ValidationFunction<boolean>;
    SendInformationNone?: ValidationFunction<boolean>;
    SendRequestDirect?: ValidationFunction<boolean>;
    SendRequestSFTP?: ValidationFunction<boolean>;
    SendRequestFHIR?: ValidationFunction<boolean>;
    SendRequestIHE?: ValidationFunction<boolean>;
    SendRequestNone?: ValidationFunction<boolean>;
    ReceiveInboundDirect?: ValidationFunction<boolean>;
    ReceiveInboundSFTP?: ValidationFunction<boolean>;
    ReceiveInboundMLLP?: ValidationFunction<boolean>;
    ReceiveInboundHTTPS?: ValidationFunction<boolean>;
    ReceiveInboundFHIR?: ValidationFunction<boolean>;
    ReceiveInboundNone?: ValidationFunction<boolean>;
    ReceiveInformationDirect?: ValidationFunction<boolean>;
    ReceiveInformationSFTP?: ValidationFunction<boolean>;
    ReceiveInformationMLLP?: ValidationFunction<boolean>;
    ReceiveInformationHTTPS?: ValidationFunction<boolean>;
    ReceiveInformationFHIR?: ValidationFunction<boolean>;
    ReceiveInformationIHE?: ValidationFunction<boolean>;
    ReceiveInformationNone?: ValidationFunction<boolean>;
    ReceiveRequestDirect?: ValidationFunction<boolean>;
    ReceiveRequestSFTP?: ValidationFunction<boolean>;
    ReceiveRequestFHIR?: ValidationFunction<boolean>;
    ReceiveRequestIHE?: ValidationFunction<boolean>;
    ReceiveRequestNone?: ValidationFunction<boolean>;
    HIPPA?: ValidationFunction<boolean>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type C4bhFormDataUpdateFormOverridesProps = {
    C4bhFormDataUpdateFormGrid?: PrimitiveOverrideProps<GridProps>;
    Participant?: PrimitiveOverrideProps<SwitchFieldProps>;
    ParticipantID?: PrimitiveOverrideProps<TextFieldProps>;
    EhrIntersystems?: PrimitiveOverrideProps<SwitchFieldProps>;
    EhrSmile?: PrimitiveOverrideProps<SwitchFieldProps>;
    EhrSalesforce?: PrimitiveOverrideProps<SwitchFieldProps>;
    EhrOther?: PrimitiveOverrideProps<TextFieldProps>;
    SendOutboundDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendOutboundSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendOutboundMLLP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendOutboundHTTPS?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendOutboundFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendOutboundNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationMLLP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationHTTPS?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInformationNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendRequestDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendRequestSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendRequestFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendRequestIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendRequestNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundMLLP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundHTTPS?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInboundNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationMLLP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationHTTPS?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveInformationNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveRequestDirect?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveRequestSFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveRequestFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveRequestIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveRequestNone?: PrimitiveOverrideProps<SwitchFieldProps>;
    HIPPA?: PrimitiveOverrideProps<SwitchFieldProps>;
} & EscapeHatchProps;
export declare type C4bhFormDataUpdateFormProps = React.PropsWithChildren<{
    overrides?: C4bhFormDataUpdateFormOverridesProps | undefined | null;
} & {
    id?: string;
    c4bhFormData?: C4bhFormData;
    onSubmit?: (fields: C4bhFormDataUpdateFormInputValues) => C4bhFormDataUpdateFormInputValues;
    onSuccess?: (fields: C4bhFormDataUpdateFormInputValues) => void;
    onError?: (fields: C4bhFormDataUpdateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: C4bhFormDataUpdateFormInputValues) => C4bhFormDataUpdateFormInputValues;
    onValidate?: C4bhFormDataUpdateFormValidationValues;
} & React.CSSProperties>;
export default function C4bhFormDataUpdateForm(props: C4bhFormDataUpdateFormProps): React.ReactElement;
