/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type C4bhUpdatedModelCreateFormInputValues = {
    User?: string;
    EHR_Vendors?: string;
    Customer_Management_System?: string;
    HIE_or_Inter?: string;
    ReceiveADTDirectSecureEmail?: boolean;
    ReceiveADTDirectEmailAddress?: string;
    ReceiveADTsFTP?: boolean;
    ReceiveADTPointToPoint?: boolean;
    ReceiveADTHTTPSnonFHIR?: boolean;
    ReceiveADTHTTPSFHIR?: boolean;
    ReceiveADTHTTPSEndpoint?: string;
    ReceiveADTOther?: boolean;
    ReceiveADTOtherDescription?: string;
    SendADTDirectSecureEmail?: boolean;
    SendADTsFTP?: boolean;
    SendADTPointToPoint?: boolean;
    SendADTHTTPSNon_FHIR?: boolean;
    SendADTHTTPS_FHIR?: boolean;
    SendADTPortal?: boolean;
    SendADTOther?: boolean;
    SendADTOtherDescribe?: string;
    RecieveInfoDirectSecureEmail?: boolean;
    RecieveInfosFTP?: boolean;
    RecieveInfoHL7V2?: boolean;
    RecieveInfoMLLP_HTTPS?: string;
    RecieveInfoThirdPartyReferral?: boolean;
    RecieveInfoThirdPartyPlatform?: string;
    RecieveInfoOther?: boolean;
    RecieveInfoOther_Describe?: string;
    RecieveInfoDirectEmailAddress?: string;
    SendInfoDirectSecureEmail?: boolean;
    SendInfosFTP?: boolean;
    SendInfoHL7v2?: boolean;
    SendInfoMLLP_HTTPS?: string;
    SendInfoThirdPartyReferral?: boolean;
    SendInfoThirdPartyPlatform?: string;
    SendInfoOther?: boolean;
    SenInfoOther_Describe?: string;
    RequestRecieveDirectSecureEmail?: boolean;
    RequestDirectEmailAddress?: string;
    RequestIHE?: boolean;
    RequestFHIR?: boolean;
    RequestOther?: boolean;
    RequestOtherDescribe?: string;
    RequestRespondDirectSecureEmail?: boolean;
    RequestRespondIHE?: boolean;
    RequestRespondFHIR?: boolean;
    RequestRespondFHIRendpoint?: string;
    RequestRespondOther?: boolean;
    RequestRespondOtherDescribe?: string;
    CoveredHIPAA?: boolean;
    HybridHIPAA?: boolean;
    AssociateHIPAA?: boolean;
    NotCoveredHIPAA?: boolean;
};
export declare type C4bhUpdatedModelCreateFormValidationValues = {
    User?: ValidationFunction<string>;
    EHR_Vendors?: ValidationFunction<string>;
    Customer_Management_System?: ValidationFunction<string>;
    HIE_or_Inter?: ValidationFunction<string>;
    ReceiveADTDirectSecureEmail?: ValidationFunction<boolean>;
    ReceiveADTDirectEmailAddress?: ValidationFunction<string>;
    ReceiveADTsFTP?: ValidationFunction<boolean>;
    ReceiveADTPointToPoint?: ValidationFunction<boolean>;
    ReceiveADTHTTPSnonFHIR?: ValidationFunction<boolean>;
    ReceiveADTHTTPSFHIR?: ValidationFunction<boolean>;
    ReceiveADTHTTPSEndpoint?: ValidationFunction<string>;
    ReceiveADTOther?: ValidationFunction<boolean>;
    ReceiveADTOtherDescription?: ValidationFunction<string>;
    SendADTDirectSecureEmail?: ValidationFunction<boolean>;
    SendADTsFTP?: ValidationFunction<boolean>;
    SendADTPointToPoint?: ValidationFunction<boolean>;
    SendADTHTTPSNon_FHIR?: ValidationFunction<boolean>;
    SendADTHTTPS_FHIR?: ValidationFunction<boolean>;
    SendADTPortal?: ValidationFunction<boolean>;
    SendADTOther?: ValidationFunction<boolean>;
    SendADTOtherDescribe?: ValidationFunction<string>;
    RecieveInfoDirectSecureEmail?: ValidationFunction<boolean>;
    RecieveInfosFTP?: ValidationFunction<boolean>;
    RecieveInfoHL7V2?: ValidationFunction<boolean>;
    RecieveInfoMLLP_HTTPS?: ValidationFunction<string>;
    RecieveInfoThirdPartyReferral?: ValidationFunction<boolean>;
    RecieveInfoThirdPartyPlatform?: ValidationFunction<string>;
    RecieveInfoOther?: ValidationFunction<boolean>;
    RecieveInfoOther_Describe?: ValidationFunction<string>;
    RecieveInfoDirectEmailAddress?: ValidationFunction<string>;
    SendInfoDirectSecureEmail?: ValidationFunction<boolean>;
    SendInfosFTP?: ValidationFunction<boolean>;
    SendInfoHL7v2?: ValidationFunction<boolean>;
    SendInfoMLLP_HTTPS?: ValidationFunction<string>;
    SendInfoThirdPartyReferral?: ValidationFunction<boolean>;
    SendInfoThirdPartyPlatform?: ValidationFunction<string>;
    SendInfoOther?: ValidationFunction<boolean>;
    SenInfoOther_Describe?: ValidationFunction<string>;
    RequestRecieveDirectSecureEmail?: ValidationFunction<boolean>;
    RequestDirectEmailAddress?: ValidationFunction<string>;
    RequestIHE?: ValidationFunction<boolean>;
    RequestFHIR?: ValidationFunction<boolean>;
    RequestOther?: ValidationFunction<boolean>;
    RequestOtherDescribe?: ValidationFunction<string>;
    RequestRespondDirectSecureEmail?: ValidationFunction<boolean>;
    RequestRespondIHE?: ValidationFunction<boolean>;
    RequestRespondFHIR?: ValidationFunction<boolean>;
    RequestRespondFHIRendpoint?: ValidationFunction<string>;
    RequestRespondOther?: ValidationFunction<boolean>;
    RequestRespondOtherDescribe?: ValidationFunction<string>;
    CoveredHIPAA?: ValidationFunction<boolean>;
    HybridHIPAA?: ValidationFunction<boolean>;
    AssociateHIPAA?: ValidationFunction<boolean>;
    NotCoveredHIPAA?: ValidationFunction<boolean>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type C4bhUpdatedModelCreateFormOverridesProps = {
    C4bhUpdatedModelCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    User?: PrimitiveOverrideProps<TextFieldProps>;
    EHR_Vendors?: PrimitiveOverrideProps<TextFieldProps>;
    Customer_Management_System?: PrimitiveOverrideProps<TextFieldProps>;
    HIE_or_Inter?: PrimitiveOverrideProps<TextFieldProps>;
    ReceiveADTDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTDirectEmailAddress?: PrimitiveOverrideProps<TextFieldProps>;
    ReceiveADTsFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTPointToPoint?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTHTTPSnonFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTHTTPSFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTHTTPSEndpoint?: PrimitiveOverrideProps<TextFieldProps>;
    ReceiveADTOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    ReceiveADTOtherDescription?: PrimitiveOverrideProps<TextFieldProps>;
    SendADTDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTsFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTPointToPoint?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTHTTPSNon_FHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTHTTPS_FHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTPortal?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendADTOtherDescribe?: PrimitiveOverrideProps<TextFieldProps>;
    RecieveInfoDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    RecieveInfosFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    RecieveInfoHL7V2?: PrimitiveOverrideProps<SwitchFieldProps>;
    RecieveInfoMLLP_HTTPS?: PrimitiveOverrideProps<TextFieldProps>;
    RecieveInfoThirdPartyReferral?: PrimitiveOverrideProps<SwitchFieldProps>;
    RecieveInfoThirdPartyPlatform?: PrimitiveOverrideProps<TextFieldProps>;
    RecieveInfoOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    RecieveInfoOther_Describe?: PrimitiveOverrideProps<TextFieldProps>;
    RecieveInfoDirectEmailAddress?: PrimitiveOverrideProps<TextFieldProps>;
    SendInfoDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInfosFTP?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInfoHL7v2?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInfoMLLP_HTTPS?: PrimitiveOverrideProps<TextFieldProps>;
    SendInfoThirdPartyReferral?: PrimitiveOverrideProps<SwitchFieldProps>;
    SendInfoThirdPartyPlatform?: PrimitiveOverrideProps<TextFieldProps>;
    SendInfoOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    SenInfoOther_Describe?: PrimitiveOverrideProps<TextFieldProps>;
    RequestRecieveDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestDirectEmailAddress?: PrimitiveOverrideProps<TextFieldProps>;
    RequestIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestOtherDescribe?: PrimitiveOverrideProps<TextFieldProps>;
    RequestRespondDirectSecureEmail?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestRespondIHE?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestRespondFHIR?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestRespondFHIRendpoint?: PrimitiveOverrideProps<TextFieldProps>;
    RequestRespondOther?: PrimitiveOverrideProps<SwitchFieldProps>;
    RequestRespondOtherDescribe?: PrimitiveOverrideProps<TextFieldProps>;
    CoveredHIPAA?: PrimitiveOverrideProps<SwitchFieldProps>;
    HybridHIPAA?: PrimitiveOverrideProps<SwitchFieldProps>;
    AssociateHIPAA?: PrimitiveOverrideProps<SwitchFieldProps>;
    NotCoveredHIPAA?: PrimitiveOverrideProps<SwitchFieldProps>;
} & EscapeHatchProps;
export declare type C4bhUpdatedModelCreateFormProps = React.PropsWithChildren<{
    overrides?: C4bhUpdatedModelCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: C4bhUpdatedModelCreateFormInputValues) => C4bhUpdatedModelCreateFormInputValues;
    onSuccess?: (fields: C4bhUpdatedModelCreateFormInputValues) => void;
    onError?: (fields: C4bhUpdatedModelCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: C4bhUpdatedModelCreateFormInputValues) => C4bhUpdatedModelCreateFormInputValues;
    onValidate?: C4bhUpdatedModelCreateFormValidationValues;
} & React.CSSProperties>;
export default function C4bhUpdatedModelCreateForm(props: C4bhUpdatedModelCreateFormProps): React.ReactElement;
