/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { AutocompleteProps, CheckboxFieldProps, DividerProps, GridProps, HeadingProps, RadioGroupFieldProps, TextFieldProps, TextProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type C4bhFormDataCreateFormInputValues = {
    ParticipantID?: string;
    EhrIntersystems?: boolean;
    EhrSmile?: boolean;
    EhrSalesforce?: boolean;
    EhrOther?: string;
    SendOutboundDirect?: boolean;
    SendOutboundSFTP?: boolean;
    SendOutboundMLLP?: boolean;
    SendOutboundHTTPS?: boolean;
    SendOutboundFHIR?: boolean;
    SendOutboundNone?: boolean;
    SendInformationDirect?: boolean;
    SendInformationSFTP?: boolean;
    SendInformationMLLP?: boolean;
    SendInformationHTTPS?: boolean;
    SendInformationFHIR?: boolean;
    SendInformationIHE?: boolean;
    SendInformationNone?: boolean;
    SendRequestDirect?: boolean;
    SendRequestSFTP?: boolean;
    SendRequestFHIR?: boolean;
    SendRequestIHE?: boolean;
    SendRequestNone?: boolean;
    ReceiveInboundDirect?: boolean;
    ReceiveInboundSFTP?: boolean;
    ReceiveInboundMLLP?: boolean;
    ReceiveInboundHTTPS?: boolean;
    ReceiveInboundFHIR?: boolean;
    ReceiveInboundNone?: boolean;
    ReceiveInformationDirect?: boolean;
    ReceiveInformationSFTP?: boolean;
    ReceiveInformationMLLP?: boolean;
    ReceiveInformationHTTPS?: boolean;
    ReceiveInformationFHIR?: boolean;
    ReceiveInformationIHE?: boolean;
    ReceiveInformationNone?: boolean;
    ReceiveRequestDirect?: boolean;
    ReceiveRequestSFTP?: boolean;
    ReceiveRequestFHIR?: boolean;
    ReceiveRequestIHE?: boolean;
    ReceiveRequestNone?: boolean;
    HIPPA?: boolean;
};
export declare type C4bhFormDataCreateFormValidationValues = {
    ParticipantID?: ValidationFunction<string>;
    EhrIntersystems?: ValidationFunction<boolean>;
    EhrSmile?: ValidationFunction<boolean>;
    EhrSalesforce?: ValidationFunction<boolean>;
    EhrOther?: ValidationFunction<string>;
    SendOutboundDirect?: ValidationFunction<boolean>;
    SendOutboundSFTP?: ValidationFunction<boolean>;
    SendOutboundMLLP?: ValidationFunction<boolean>;
    SendOutboundHTTPS?: ValidationFunction<boolean>;
    SendOutboundFHIR?: ValidationFunction<boolean>;
    SendOutboundNone?: ValidationFunction<boolean>;
    SendInformationDirect?: ValidationFunction<boolean>;
    SendInformationSFTP?: ValidationFunction<boolean>;
    SendInformationMLLP?: ValidationFunction<boolean>;
    SendInformationHTTPS?: ValidationFunction<boolean>;
    SendInformationFHIR?: ValidationFunction<boolean>;
    SendInformationIHE?: ValidationFunction<boolean>;
    SendInformationNone?: ValidationFunction<boolean>;
    SendRequestDirect?: ValidationFunction<boolean>;
    SendRequestSFTP?: ValidationFunction<boolean>;
    SendRequestFHIR?: ValidationFunction<boolean>;
    SendRequestIHE?: ValidationFunction<boolean>;
    SendRequestNone?: ValidationFunction<boolean>;
    ReceiveInboundDirect?: ValidationFunction<boolean>;
    ReceiveInboundSFTP?: ValidationFunction<boolean>;
    ReceiveInboundMLLP?: ValidationFunction<boolean>;
    ReceiveInboundHTTPS?: ValidationFunction<boolean>;
    ReceiveInboundFHIR?: ValidationFunction<boolean>;
    ReceiveInboundNone?: ValidationFunction<boolean>;
    ReceiveInformationDirect?: ValidationFunction<boolean>;
    ReceiveInformationSFTP?: ValidationFunction<boolean>;
    ReceiveInformationMLLP?: ValidationFunction<boolean>;
    ReceiveInformationHTTPS?: ValidationFunction<boolean>;
    ReceiveInformationFHIR?: ValidationFunction<boolean>;
    ReceiveInformationIHE?: ValidationFunction<boolean>;
    ReceiveInformationNone?: ValidationFunction<boolean>;
    ReceiveRequestDirect?: ValidationFunction<boolean>;
    ReceiveRequestSFTP?: ValidationFunction<boolean>;
    ReceiveRequestFHIR?: ValidationFunction<boolean>;
    ReceiveRequestIHE?: ValidationFunction<boolean>;
    ReceiveRequestNone?: ValidationFunction<boolean>;
    HIPPA?: ValidationFunction<boolean>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type C4bhFormDataCreateFormOverridesProps = {
    C4bhFormDataCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    SectionalElement0?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement5?: PrimitiveOverrideProps<DividerProps>;
    ParticipantID?: PrimitiveOverrideProps<AutocompleteProps>;
    SectionalElement1?: PrimitiveOverrideProps<TextProps>;
    SectionalElement4?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement3?: PrimitiveOverrideProps<TextProps>;
    RowGrid6?: PrimitiveOverrideProps<GridProps>;
    EhrIntersystems?: PrimitiveOverrideProps<CheckboxFieldProps>;
    EhrSmile?: PrimitiveOverrideProps<CheckboxFieldProps>;
    EhrSalesforce?: PrimitiveOverrideProps<CheckboxFieldProps>;
    EhrOther?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement7?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement8?: PrimitiveOverrideProps<TextProps>;
    RowGrid10?: PrimitiveOverrideProps<GridProps>;
    SendOutboundDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendOutboundSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendOutboundMLLP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendOutboundHTTPS?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendOutboundFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendOutboundNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement9?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement10?: PrimitiveOverrideProps<TextProps>;
    RowGrid13?: PrimitiveOverrideProps<GridProps>;
    SendInformationDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationMLLP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationHTTPS?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationIHE?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendInformationNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement11?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement12?: PrimitiveOverrideProps<TextProps>;
    RowGrid16?: PrimitiveOverrideProps<GridProps>;
    SendRequestDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendRequestSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendRequestFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendRequestIHE?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SendRequestNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement13?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement14?: PrimitiveOverrideProps<TextProps>;
    RowGrid19?: PrimitiveOverrideProps<GridProps>;
    ReceiveInboundDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInboundSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInboundMLLP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInboundHTTPS?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInboundFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInboundNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement15?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement16?: PrimitiveOverrideProps<TextProps>;
    RowGrid22?: PrimitiveOverrideProps<GridProps>;
    ReceiveInformationDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationMLLP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationHTTPS?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationIHE?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveInformationNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement18?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement17?: PrimitiveOverrideProps<TextProps>;
    RowGrid25?: PrimitiveOverrideProps<GridProps>;
    ReceiveRequestDirect?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveRequestSFTP?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveRequestFHIR?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveRequestIHE?: PrimitiveOverrideProps<CheckboxFieldProps>;
    ReceiveRequestNone?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement19?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement6?: PrimitiveOverrideProps<TextProps>;
    HIPPA?: PrimitiveOverrideProps<RadioGroupFieldProps>;
} & EscapeHatchProps;
export declare type C4bhFormDataCreateFormProps = React.PropsWithChildren<{
    overrides?: C4bhFormDataCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: C4bhFormDataCreateFormInputValues) => C4bhFormDataCreateFormInputValues;
    onSuccess?: (fields: C4bhFormDataCreateFormInputValues) => void;
    onError?: (fields: C4bhFormDataCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: C4bhFormDataCreateFormInputValues) => C4bhFormDataCreateFormInputValues;
    onValidate?: C4bhFormDataCreateFormValidationValues;
} & React.CSSProperties>;
export default function C4bhFormDataCreateForm(props: C4bhFormDataCreateFormProps): React.ReactElement;
