/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { CheckboxFieldProps, DividerProps, GridProps, HeadingProps, RadioGroupFieldProps, TextFieldProps, TextProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type DSAInfoFormInputValues = {
    Participant?: string;
    Field1?: string;
    Field2?: boolean;
    Field3?: boolean;
    Field4?: boolean;
    Field6?: string[];
    Field5?: boolean;
    Field7?: boolean;
    Field8?: boolean;
    Field9?: boolean;
    Field10?: boolean;
    Field11?: boolean;
    Field13?: boolean;
    Field14?: boolean;
    Field15?: boolean;
    Field16?: boolean;
    Field17?: boolean;
    Field18?: boolean;
    Field19?: boolean;
    Field12?: boolean;
    Field20?: boolean;
    Field21?: boolean;
    Field22?: boolean;
    Field23?: boolean;
    Field24?: boolean;
    Field25?: boolean;
    Field26?: boolean;
    Field27?: boolean;
    Field28?: boolean;
    Field29?: boolean;
    Field30?: boolean;
    Field31?: boolean;
    Field32?: boolean;
    Field33?: boolean;
    Field34?: boolean;
    Field35?: boolean;
    Field36?: boolean;
    Field37?: boolean;
    Field38?: boolean;
    Field39?: boolean;
    Field40?: boolean;
    Field41?: boolean;
    Field42?: string;
};
export declare type DSAInfoFormValidationValues = {
    Participant?: ValidationFunction<string>;
    Field1?: ValidationFunction<string>;
    Field2?: ValidationFunction<boolean>;
    Field3?: ValidationFunction<boolean>;
    Field4?: ValidationFunction<boolean>;
    Field6?: ValidationFunction<string>;
    Field5?: ValidationFunction<boolean>;
    Field7?: ValidationFunction<boolean>;
    Field8?: ValidationFunction<boolean>;
    Field9?: ValidationFunction<boolean>;
    Field10?: ValidationFunction<boolean>;
    Field11?: ValidationFunction<boolean>;
    Field13?: ValidationFunction<boolean>;
    Field14?: ValidationFunction<boolean>;
    Field15?: ValidationFunction<boolean>;
    Field16?: ValidationFunction<boolean>;
    Field17?: ValidationFunction<boolean>;
    Field18?: ValidationFunction<boolean>;
    Field19?: ValidationFunction<boolean>;
    Field12?: ValidationFunction<boolean>;
    Field20?: ValidationFunction<boolean>;
    Field21?: ValidationFunction<boolean>;
    Field22?: ValidationFunction<boolean>;
    Field23?: ValidationFunction<boolean>;
    Field24?: ValidationFunction<boolean>;
    Field25?: ValidationFunction<boolean>;
    Field26?: ValidationFunction<boolean>;
    Field27?: ValidationFunction<boolean>;
    Field28?: ValidationFunction<boolean>;
    Field29?: ValidationFunction<boolean>;
    Field30?: ValidationFunction<boolean>;
    Field31?: ValidationFunction<boolean>;
    Field32?: ValidationFunction<boolean>;
    Field33?: ValidationFunction<boolean>;
    Field34?: ValidationFunction<boolean>;
    Field35?: ValidationFunction<boolean>;
    Field36?: ValidationFunction<boolean>;
    Field37?: ValidationFunction<boolean>;
    Field38?: ValidationFunction<boolean>;
    Field39?: ValidationFunction<boolean>;
    Field40?: ValidationFunction<boolean>;
    Field41?: ValidationFunction<boolean>;
    Field42?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type DSAInfoFormOverridesProps = {
    DSAInfoFormGrid?: PrimitiveOverrideProps<GridProps>;
    SectionalElement0?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement1?: PrimitiveOverrideProps<TextProps>;
    Participant?: PrimitiveOverrideProps<RadioGroupFieldProps>;
    SectionalElement5?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement4?: PrimitiveOverrideProps<DividerProps>;
    Field1?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement20?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement3?: PrimitiveOverrideProps<TextProps>;
    RowGrid8?: PrimitiveOverrideProps<GridProps>;
    Field2?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field3?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field4?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field6?: PrimitiveOverrideProps<TextFieldProps>;
    SectionalElement6?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement11?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement9?: PrimitiveOverrideProps<TextProps>;
    RowGrid13?: PrimitiveOverrideProps<GridProps>;
    Field5?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field7?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field8?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field9?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field10?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field11?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement7?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement8?: PrimitiveOverrideProps<TextProps>;
    RowGrid16?: PrimitiveOverrideProps<GridProps>;
    Field13?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field14?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field15?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field16?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field17?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field18?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field19?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement17?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement10?: PrimitiveOverrideProps<TextProps>;
    RowGrid19?: PrimitiveOverrideProps<GridProps>;
    Field12?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field20?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field21?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field22?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field23?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement12?: PrimitiveOverrideProps<HeadingProps>;
    SectionalElement13?: PrimitiveOverrideProps<TextProps>;
    RowGrid22?: PrimitiveOverrideProps<GridProps>;
    Field24?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field25?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field26?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field27?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field28?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field29?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement19?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement14?: PrimitiveOverrideProps<TextProps>;
    RowGrid25?: PrimitiveOverrideProps<GridProps>;
    Field30?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field31?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field32?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field33?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field34?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field35?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field36?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement18?: PrimitiveOverrideProps<DividerProps>;
    SectionalElement15?: PrimitiveOverrideProps<TextProps>;
    RowGrid28?: PrimitiveOverrideProps<GridProps>;
    Field37?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field38?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field39?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field40?: PrimitiveOverrideProps<CheckboxFieldProps>;
    Field41?: PrimitiveOverrideProps<CheckboxFieldProps>;
    SectionalElement16?: PrimitiveOverrideProps<HeadingProps>;
    Field42?: PrimitiveOverrideProps<RadioGroupFieldProps>;
    SectionalElement2?: PrimitiveOverrideProps<TextProps>;
} & EscapeHatchProps;
export declare type DSAInfoFormProps = React.PropsWithChildren<{
    overrides?: DSAInfoFormOverridesProps | undefined | null;
} & {
    onSubmit: (fields: DSAInfoFormInputValues) => void;
    onChange?: (fields: DSAInfoFormInputValues) => DSAInfoFormInputValues;
    onValidate?: DSAInfoFormValidationValues;
} & React.CSSProperties>;
export default function DSAInfoForm(props: DSAInfoFormProps): React.ReactElement;
